### ISSUE TITLE
possible dead lock?

### ISSUE THREAD

**Issue by Sciss** [Sciss/Model#2]
Found this - which comes though after putting the laptop to sleep and probably killing jackd or scsynth:

```

Found one Java-level deadlock:
=============================
"Thread-6":
  waiting to lock monitor 0x00007f7414004838 (object 0x00000005cc233a10, a java.lang.Object),
  which is held by "AWT-EventQueue-1"
"AWT-EventQueue-1":
  waiting to lock monitor 0x00007f73d4006c38 (object 0x00000005cc0eb6a0, a java.lang.Object),
  which is held by "Thread-6"
```

Here are the details:

```
"Thread-6" #40 prio=5 os_prio=0 tid=0x00007f7418057800 nid=0x3cbc waiting for monitor entry [0x00007f742e3fe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at de.sciss.synth.swing.j.JServerStatusPanel.server_$eq(JServerStatusPanel.scala:174)
	- waiting to lock <0x00000005cc233a10> (a java.lang.Object)
	at de.sciss.synth.swing.j.JServerStatusPanel$$anonfun$2.applyOrElse(JServerStatusPanel.scala:161)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at de.sciss.model.impl.ModelImpl.$anonfun$dispatch$1(ModelImpl.scala:38)
	at de.sciss.model.impl.ModelImpl.$anonfun$dispatch$1$adapted(ModelImpl.scala:36)
	at de.sciss.model.impl.ModelImpl$$Lambda$332/1556502249.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at de.sciss.model.impl.ModelImpl.dispatch(ModelImpl.scala:36)
	- locked <0x00000005cc0eb6a0> (a java.lang.Object)
	at de.sciss.model.impl.ModelImpl.dispatch$(ModelImpl.scala:35)
	at de.sciss.synth.impl.ServerImpl.dispatch(ServerImpl.scala:397)
	at de.sciss.synth.impl.OnlineServerImpl.condition_$eq(ServerImpl.scala:201)
	- locked <0x00000005cc0ec3f0> (a java.lang.Object)
	at de.sciss.synth.impl.OnlineServerImpl.serverOffline(ServerImpl.scala:126)
	- locked <0x00000005cc0ec3f0> (a java.lang.Object)
	at de.sciss.synth.impl.ConnectionLike.$anonfun$abort$1(Connection.scala:56)
	at de.sciss.synth.impl.ConnectionLike.$anonfun$abort$1$adapted(Connection.scala:54)
	at de.sciss.synth.impl.ConnectionLike$$Lambda$1313/408970858.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:257)
	at de.sciss.synth.impl.ConnectionLike.abort(Connection.scala:54)
	at de.sciss.synth.impl.ConnectionLike.abort$(Connection.scala:52)
	at de.sciss.synth.impl.Booting.abort(Connection.scala:169)
	at de.sciss.synth.impl.Booting$$anon$1.run(Connection.scala:203)
```

and

```
"pool-1-thread-1" #38 prio=5 os_prio=0 tid=0x00007f74620e1800 nid=0x3cb9 waiting for monitor entry [0x00007f742e701000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at de.sciss.model.impl.ModelImpl.removeListener(ModelImpl.scala:58)
	- waiting to lock <0x00000005cc0eb6a0> (a java.lang.Object)
	at de.sciss.model.impl.ModelImpl.removeListener$(ModelImpl.scala:57)
	at de.sciss.synth.impl.ServerImpl.removeListener(ServerImpl.scala:397)
	at de.sciss.synth.proc.impl.AuralSystemImpl$Impl$StateRunning.$anonfun$dispose$5(AuralSystemImpl.scala:108)
	at de.sciss.synth.proc.impl.AuralSystemImpl$Impl$StateRunning$$Lambda$1320/360547867.apply$mcV$sp(Unknown Source)
	at de.sciss.synth.proc.impl.AuralSystemImpl$$anon$1.run(AuralSystemImpl.scala:45)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sciss** [comment]
should be fixed, at least for invocations of `dispatch`
